INSERT INTO HUB VALUES ('HUB1',1,4);

INSERT INTO APP.UNIDADRESIDENCIAL (ID, ACTIVADO, BARRIO, DIRECCION, IDHUB, "NAME") 
	VALUES ('UniRes1', 1, 'Chapinero', 'Calle 7', 'Hub1', 'Bambu');
INSERT INTO APP.UNIDADRESIDENCIAL (ID, ACTIVADO, BARRIO, DIRECCION, IDHUB, "NAME") 
	VALUES ('UniRes2', 1, 'Chapinero', 'Calle 7', 'Hub1', 'Altaloma2');
INSERT INTO APP.UNIDADRESIDENCIAL (ID, ACTIVADO, BARRIO, DIRECCION, IDHUB, "NAME") 
	VALUES ('UniRes3', 1, 'Modelia', 'Calle 26', 'Hub1', 'Edificios');


INSERT INTO APP.INMUEBLE (ID, ACTIVADO, IDUNIDAD, PROPIETARIO,TELPROPIETARIO,EMAILPROPIETARIO) 
	VALUES ('Inmueble1', 1, 'UniRes1', 'Kelly1','3192224444','kelly1@gmail.com');
INSERT INTO APP.INMUEBLE (ID, ACTIVADO, IDUNIDAD, PROPIETARIO,TELPROPIETARIO,EMAILPROPIETARIO) 
	VALUES ('Inmueble2', 1, 'UniRes1', 'Kelly2','3197778884','kelly2@gmail.com');
INSERT INTO APP.INMUEBLE (ID, ACTIVADO, IDUNIDAD, PROPIETARIO,TELPROPIETARIO,EMAILPROPIETARIO) 
	VALUES ('Inmueble3', 1, 'UniRes1', 'Kelly3','3196664444','kelly3@gmail.com');
INSERT INTO APP.INMUEBLE (ID, ACTIVADO, IDUNIDAD, PROPIETARIO,TELPROPIETARIO,EMAILPROPIETARIO) 
	VALUES ('Inmueble4', 1, 'UniRes1', 'Kelly4','3195554444','kelly4@gmail.com');

INSERT INTO APP.SENSOR (ID, ACTIVADO, IDINMUEBLE, MAXINTENTOSFALLIDOS,LAT,LON) 
	VALUES ('Sensor1', 1, 'Inmueble1', 4,'4.920055', '-74.043354');
INSERT INTO APP.SENSOR (ID, ACTIVADO, IDINMUEBLE, MAXINTENTOSFALLIDOS,LAT,LON) 
	VALUES ('Sensor2', 1, 'Inmueble2', 5,'4.920605', '-74.043236');
INSERT INTO APP.SENSOR (ID, ACTIVADO, IDINMUEBLE, MAXINTENTOSFALLIDOS,LAT,LON) 
	VALUES ('Sensor3', 1, 'Inmueble3', 7,'4.921113', '-74.043139');
INSERT INTO APP.SENSOR (ID, ACTIVADO, IDINMUEBLE, MAXINTENTOSFALLIDOS,LAT,LON) 
	VALUES ('Sensor4', 1, 'Inmueble4', 2,'4.921054', '-74.042774');
INSERT INTO APP.SENSOR (ID, ACTIVADO, IDINMUEBLE, MAXINTENTOSFALLIDOS,LAT,LON) 
	VALUES ('Sensor5', 1, 'Inmueble1', 3,'4.920095', '-74.043388');



